### ISSUE TITLE
Fix complexities for BPI_2014

### ISSUE THREAD

**Issue by andreamalhera** [lmu-dbs/feeed#8]

**Comment by christianmaxmike** [comment]
Math Domain Error: 
- Another error which occurs is a math domain error because there is a zero value as input to the log function math.log(e). More specifically, it occurs again in the feeed package in the module complexity.py
- The problem is the line (last_timestamp - event.timestamp).total_seconds() / timespan : Whenever the nominator equals the timespan (denominator), it results to 1, which then results in a 0.0 value. For some reasons timestamps are the same for all events ( I will append a snapshot).
- In my runs the error occurred just for the linear forgetting branch, hence in the lines 390 and 401 in the complexity.py module.
- My workaround for this issue was the following -> I just add a little epsilon value:
   - (last_timestamp - event.timestamp).total_seconds() / (timespan+1e-6)

**Comment by christianmaxmike** [comment]
For: 
https://github.com/lmu-dbs/feeed/blob/5e062e9c839d8943bd1950347598e08e2cc3ae99/feeed/complexity.py#L400

```
log_complexity_linear += (
                    1 - (last_timestamp - event.timestamp).total_seconds() / (timespan+1e-6)
                )
```

For: 
https://github.com/lmu-dbs/feeed/blob/5e062e9c839d8943bd1950347598e08e2cc3ae99/feeed/complexity.py#L410
```
e += (
                        1
                        - (last_timestamp - event.timestamp).total_seconds() / (timespan+1e-6)
                    )
```

**Comment by Niklkind** [comment]
@christianmaxmike Thank you for your comment, I added some exception handling for this error using your workaround.
